### ISSUE TITLE
CreditMemo Data ?

### ISSUE THREAD

**Issue by prigal** [Sylius/RefundPlugin#106]
Hello,

Invoicing plugin has billing_data to store some information of the buyer. Why don't we do the same here in credit memo ?

As it, plugin won't be used without being extended by companies as long as the customer data should be present on the credit memo to be valid (if I'm not wrong !).

NB : That leads to an other question for seller data. In invoicing plugin they come from channel, that's right, but there are not stored in billing_data and I think we should store them, If channel billing data change, and user come to download his invoices, they won't be the same as original.

**Comment by prigal** [comment]
Reference to issue in InvoicingPlugin : https://github.com/Sylius/InvoicingPlugin/issues/91

**Comment by Zales0123** [comment]
Hello @prigal, thank you for your opinion, it's pretty valuable :) We decided to extract shop billing data into the Sylius core, as it's a quite common use case. Then, we will be able to use this data both here and in `InvoicingPlugin` 🐎

**Comment by prigal** [comment]
Hello @Zales0123, to understand, we will have billing data on channel (in core) and both plugins will store these data when document (invoice / creditmemo) is created so they become immutable per document. Right ?

**Comment by Zales0123** [comment]
Exactly 👍

**Comment by prigal** [comment]
Any idea of when all of this will be done on your side ? 
1. Modification of core
2. Invoice plugin modification
3. Refund plugin modification 
Maybe we can help as long as we initially plan to do it too on our side.

**Comment by Zales0123** [comment]
PR to the core is already done (https://github.com/Sylius/Sylius/pull/10079), sadly we need to wait for the Sylius 1.4 release (at the end of the month) and there is no way to speed it up. This is the main blocker. `InvoicePlugin` and `RefundPlugin` modifications will be done in the meantime, but of course, we're always happy to accept some contributions from the community :)

**Comment by prigal** [comment]
@Zales0123 after some time thinking about the model and how we will do it on our side, I suggest you some modifications for the core PR. 

Adding billing data to channel is not really correct, as long as a channel is a "way for selling goods". A same company can have several channels : online shop, API, mobile app, physical store, ... that all share the same billing data. 

We can duplicate data, but in my opinion we should add a higher level in Sylius : a "company" entity. The company will store the billing data, and we will select per channel which is the company that "run" the channel.

When it comes to exporting data to a accounting software / ERP. You will need to export it "per company" and not really "per channel".
