### ISSUE TITLE
Release stable RefundPlugin

### ISSUE THREAD

**Issue by pamil** [Sylius/RefundPlugin#116]
This is a meta-issue to coordinate efforts towards releasing a stable version of this plugin. Stay tuned!

**Comment by Trofim234** [comment]
Как пробить номер?

**Comment by Zales0123** [comment]
Hello @Trofim234, could you please repeat your question in English? It's used for the communication on all Sylius repositories as it is understandable for most of the contributors :)

**Comment by TheDevilOnLine** [comment]
@pamil is there a todo list of things that need to happen to make the plugin stable and/or compatible with 1.7?

**Comment by GSadee** [comment]
I'm closing this issue as the stable RefundPlugin has been released
