### ISSUE TITLE
Doctrine Migration script Version20180718125528 is not working 

### ISSUE THREAD

**Issue by tom10271** [Sylius/RefundPlugin#147]
As in Version20180704112314 and not sure exactly why it uses `utf8mb4` encoding. (Potentially related to the change on default encoding in doctrine 2.5, https://github.com/doctrine/orm/issues/7416#issuecomment-425778627)

In `Version20180704112314`:

By replacing

```php
$this->addSql('CREATE TABLE sylius_refund_refund (id INT AUTO_INCREMENT NOT NULL, orderNumber VARCHAR(255) NOT NULL, amount INT NOT NULL, refundedUnitId INT DEFAULT NULL, PRIMARY KEY(id))');
```

with
```php
$this->addSql('CREATE TABLE sylius_refund_refund (id INT AUTO_INCREMENT NOT NULL, orderNumber VARCHAR(255) NOT NULL, amount INT NOT NULL, refundedUnitId INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE UTF8_unicode_ci ENGINE = InnoDB');
```

fixes the problem

https://github.com/Sylius/RefundPlugin/pull/148

**Comment by pamil** [comment]
Fixed after #148.
