### ISSUE TITLE
Replace Address::getFirstName . getLastName with Address::getFullName

### ISSUE THREAD

**Issue by diimpp** [Sylius/RefundPlugin#192]
https://github.com/Sylius/RefundPlugin/blob/1886a1bb2894599c93955016f270610ac2bdfb5c/src/Generator/CreditMemoGenerator.php#L89

**Comment by Zales0123** [comment]
👍 are you willing to open a PR with such a fix?

**Comment by diimpp** [comment]
Yes, in time. I'm more worried about other issues, that I've recently opened

**Comment by diimpp** [comment]
Actually, problem is deeper. `CustomerBillingAddress` should have proper `firstname` and `lastname` properties, not single `name`. It's the way for Sylius Address, Customer and InvoicingPlugin BillingAddress
