### ISSUE TITLE
[Sylius 1.7] locale filter not found

### ISSUE THREAD

**Issue by Prometee** [Sylius/RefundPlugin#201]
While testing Sylius 1.7 I encountered an error into the administration on `sylius_refund_order_refunds_list` route

```
Unknown "locale" filter. Did you mean "locale_name", "sylius_locale_name", "sylius_locale_country"?
```

This occurred because of a filter used in `vendor/sylius/refund-plugin/src/Resources/views/orderRefunds.html.twig` line 29.

I don't know if it was an old Sylius Twig filter or a Twig add-on one, but maybe this filter can be deleted ?

**Comment by tuala** [comment]
Yes it can and should, you can create a PR and override the template on your project in the mean time (templates/bundles/SyliusRefundPlugin/orderRefunds.html.twig). I had the same problem in _header.html.twig and used  "sylius_locale_country" which displays both locale and country name.

**Comment by Zales0123** [comment]
Generally, we should make `RefundPlugin` compatible with Sylius 1.7, as it is right now [based on Sylius 1.5](https://github.com/Sylius/RefundPlugin/blob/master/composer.json#L26) (which is not maintained anymore 😕)
