### ISSUE TITLE
Impossible to pass specific data to the email

### ISSUE THREAD

**Issue by Nek-** [Sylius/RefundPlugin#218]
The plugin enforce whole redefinition (obviously by copy/pasting) of the CreditMemoEmailSender. This is sad. It should not be final and have a protected method like `getEmailData()`.

https://github.com/Sylius/RefundPlugin/blob/master/src/Sender/CreditMemoEmailSender.php

**Comment by GSadee** [comment]
The `CreditMemoEmailSender` service doesn't look very big, it has separated responsibilities and in fact, it only facilitates communication. I would recommend the concept of [decorating the service](https://symfony.com/doc/current/service_container/service_decoration.html).
