### ISSUE TITLE
[UI/UX] Refund float price

### ISSUE THREAD

**Issue by Jibbarth** [Sylius/RefundPlugin#225]
Hey :wave: 

We noticed that when using comma in input instead of dot during the refund process, we lose the decimal part of price. 

I suggest to use `<input type="number" step="0.01 ../>`, that should send a correct float number to controller and no lose decimal part of price. The `type=number` display and understand number in browser locale, so user that use comma could keep using them. 

The change should be done in template `src/Resources/views/_shipping.html.twig` and `src/Resources/views/_unitInput.html.twig`

WDYT ? I could provide a PR if you think this is something we should care about.

**Comment by GSadee** [comment]
Hello @Jibbarth 

The changes you suggest seem to make sense and can fix some unexpected behaviour during refunding, feel free to open a PR with such changes 😃

**Comment by GSadee** [comment]
Fixed by #234
