### ISSUE TITLE
Updating stock after a refund

### ISSUE THREAD

**Issue by programm-er** [Sylius/RefundPlugin#226]
Hi

First of all great plugin.

I need to do some customization to the logic per my use case. I want to be able to update back the stock of the products refunded but I am not able to figure out if the plugin itself provides such functionality or if there is a way to implement this feature through an event handler.

In both cases are there any pointers to the docs that I can check.

As I mention i want to be able to update back -increasing the units available for the products refunded.

Thanks.

**Comment by GSadee** [comment]
After looking at the [features scenarios](https://github.com/Sylius/RefundPlugin/tree/master/features), it seems that described by you behaviour is not implemented in this plugin. I guess that the main reason behind this is that we have no information what the reason for the return was. I would recommend you to implement that feature by myself. One of the helpful classes could be [InventoryOperator from Sylius/Sylius](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Inventory/Operator/OrderInventoryOperator.php).
