### ISSUE TITLE
[AdminUI/Order/Refunds] Original payment method detection is incorrect

### ISSUE THREAD

**Issue by diimpp** [Sylius/RefundPlugin#233]
In case when there are multiple payment attempts in different states and possibly with different payment methods

https://github.com/Sylius/RefundPlugin/blob/02d9399de33789b9dd2d9bb431fec89576540361/src/Resources/views/_paymentMethod.html.twig#L2

then this code doesn't work as intended and should be replaced with

```twig
{% set original_payment_method = order.lastPayment(constant('Sylius\\Component\\Core\\Model\\PaymentInterface::STATE_COMPLETED')).method %}
```
as something not outright broken.

Ideally it should be done as new provider and twig function, which can accommodate partial states as well.

![image](https://user-images.githubusercontent.com/870747/100571660-3bbd1580-3306-11eb-8d43-43b016ff05c8.png)
![image](https://user-images.githubusercontent.com/870747/100571600-1defb080-3306-11eb-98ec-8280d5ed133f.png)

**Comment by GSadee** [comment]
Fixed by https://github.com/Sylius/RefundPlugin/pull/316
