### ISSUE TITLE
French translation missing

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/RefundPlugin#247]
After Install , i have something like the image below:

![Screenshot from 2021-01-19 09-44-15](https://user-images.githubusercontent.com/40351002/104997946-7f491b80-5a3b-11eb-91eb-1f1dd2870085.png)
![Screenshot from 2021-01-19 09-40-57](https://user-images.githubusercontent.com/40351002/104997952-8112df00-5a3b-11eb-8f5b-bcc0040a1b98.png)

**Comment by Zales0123** [comment]
Hello @SylvanoTombo! The PR with missing French translations was already merged https://github.com/Sylius/RefundPlugin/pull/217, but the version with it has not been released yet. It will be included in the upcoming release 🖖

**Comment by SylvanoTombo** [comment]
@Zales0123 , Thanks!
