### ISSUE TITLE
You can refund a 100% discounted shipment

### ISSUE THREAD

**Issue by blackshadev** [Sylius/RefundPlugin#252]
## context

At our webshop we have a promotion rule to discount the shipment of an order 100% if the order amount is above 30,-.
I noticed at the refunds menu, one can actually refund the full shipment costs even though it was 100% discounted. 
I also checked if other promotions are  being considered, which worked  fine. So this seems specific to the shipment.

## Reproduction

- Add a promotional rule which 100% discounts shipping
- Create an order (notice you have 100% discount on shipping)
- Mark the order as paid
- Go to the refunds page of said order
- See you can refund the full price of the shipment

## versions

- sylius/refund-plugin: v1.0.0-RC.4
- sylius/sylius: v1.8.8
- sylius/plus: v0.32.0

**Comment by vasiliucatalinmihai** [comment]
Yep, same issue. The promotions on shipping are not considered.
As a fix I did this (maybe helps you):
In `Sylius\RefundPlugin\Provider\RemainingTotalProvider::getRefundUnitTotal` the shipment does not contains the promotions
so overwrite the method and replace
`return $shipment->getAmount();`

with
```
$order = $shipment->getAdjustable();
if ($order instanceof OrderInterface) {
      return $order->getShippingTotal();
}

return $shipment->getAmount();
```


also you need in your templates overwrite the `vendor/sylius/refund-plugin/src/Resources/views/_shipping.html.twig` replace `shipment.amount` with `order.getShippingTotal` at line 10 and 25.

Hope it helps :D
