### ISSUE TITLE
[StateResolver\RefundedStateResolver] logic error in checking order payment state

### ISSUE THREAD

**Issue by petar-locastic** [Sylius/RefundPlugin#253]
In StateResolver\RefundedStateResolver:50, `OrderPaymentStates::STATE_REFUNDED === $order->getState() `can't be TRUE, and it should be changed to `OrderPaymentStates::STATE_REFUNDED === $order->getPaymentState()`

**Comment by diimpp** [comment]
Yep, that's an artifact from times, where this plugin offered `refunded` state on order sm, not order payment sm
