### ISSUE TITLE
Sylius 1.8 compatibility issue

### ISSUE THREAD

**Issue by Nek-** [Sylius/RefundPlugin#258]
The following line calls a method that does not exist in Sylius 1.8:

https://github.com/Sylius/RefundPlugin/blob/2a93f556a712b6fbdd7f17bc45e9bbce17f1660b/src/OrderProcessor/ShippingChargesProcessor.php#L58

**Comment by GSadee** [comment]
Hi @Nek-, did you follow the instructions from [UPGRADE file](https://github.com/Sylius/RefundPlugin/blob/master/UPGRADE.md#upgrade-from-100-rc5-to-100-rc6)? There is a point for adding traits that enhance Adjustment and Shipment models.

**Comment by Nek-** [comment]
Oh. That's new. New like I opened the upgrade page at the start of the week, and I should have to refresh it.

**Comment by dan-payplug** [comment]
Hello @GSadee,

I had the same issue. Could you please update your README.md to clearly refer to [UPGRADE.md](https://github.com/Sylius/RefundPlugin/blob/master/UPGRADE.md#upgrade-from-100-rc5-to-100-rc6) file ?

I have wasted a lot of time to find what was wrong with the refund plugin :)

Thank you ! 😄 

Best regards

**Comment by dan-payplug** [comment]
Hello again,

When I try to install refund-plugin on Docker that run on Sylius 1.8.6, I have this error : 

```
sylius_1    | Warning! This action will erase your database.
sylius_1    |  0/1 [░                           ]   0%
sylius_1    | In ShippingChargesProcessor.php line 58:
sylius_1    |                                                                                
sylius_1    |   Attempted to call an undefined method named "removeAdjustments" of class "A  
sylius_1    |   pp\Entity\Shipping\Shipment".                                                
sylius_1    |                                                                                
sylius_1    | 
```

Any tips please ?

Thank you

**Comment by Nek-** [comment]
@dan-payplug , it's the part containing code sample. You just have to read.

**Comment by dan-payplug** [comment]
Hello yes,

I understand perfectly, I just detailed the error that you already have retrieve above.

Will it be fix in a next PR ?

Thank you

I

**Comment by Nek-** [comment]
It's not an issue. I just do not close it so people can see it's not an issue and go directly to the upgrade file after seeing this issue. So no, it will not be "fixed". Besides, it seems this will not be to do with Sylius 1.9.

**Comment by dan-payplug** [comment]
Sorry,

But it is not clear for me.

Why are you referring to your [UPGRADE.md](https://github.com/Sylius/RefundPlugin/blob/master/UPGRADE.md#upgrade-from-100-rc5-to-100-rc6) ?

If I install for the first time the refund-plugin on my setup running on Sylius 1.8.x, I will only follow step from [README.md](https://github.com/Sylius/RefundPlugin/blob/master/README.md) installation, that's all.

> it seems this will not be to do with Sylius 1.9

 it's not a clear answer to my problem and for people who try using this plugin fro the firstime.

Regards

**Comment by Nek-** [comment]
Closing since people seems to understand there is actually an issue and there's not. Everything is described in the UPGRADE file.
