### ISSUE TITLE
Cannot Refund shipping when all items are refunded

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/RefundPlugin#262]
Sylius version: 1.7

When all product items are refunded, the button refund is disabled even if the shipping is not refunded

![image](https://user-images.githubusercontent.com/40351002/110296965-ff373f00-8003-11eb-8db6-1605c68e2cb2.png)

**Comment by GSadee** [comment]
Hello @SylvanoTombo, I've tried to reproduce the problem on our [demo](https://master.demo.sylius.com/admin/), but it seems to be working as it should be. Could you describe all the steps to achieve that behaviour? What is more, Sylius 1.7 is no longer supported in the newest versions of this plugin.

**Comment by SylvanoTombo** [comment]
Hello @GSadee , i see in your demo and it work great! i am using version 0.10.1 of the plugin.. when i refund all order items, the order state is refunded and the refund button is disabled while I have not yet refunded the shipping

**Comment by SylvanoTombo** [comment]
@GSadee , i think, it's due to the shipping percentage discount!

**Comment by SylvanoTombo** [comment]
I think , it's related to #252
