### ISSUE TITLE
Credit memo improvements

### ISSUE THREAD

**Issue by Zales0123** [Sylius/RefundPlugin#27]
`CreditMemo` should have similar fields as `Invoice` from [InvoicingPlugin](https://github.com/Sylius/InvoicingPlugin/blob/master/src/Entity/Invoice.php). Right now it's far from perfect (it's just too simple)

**Comment by Zales0123** [comment]
IMO it's pretty good right now (lots of fields added to `CreditMemo` since it's issue opening). We could open some more specific issues about missing fields if required :)

**Comment by prigal** [comment]
@Zales0123 maybe we could reopen this discussion :)

Adding billing data and make it immutable is already discussed and validated in an other issue but, why do you decide to do invoice_items in invoice plugin and keep data jsonified in credit_memo ? (why non credit_memo_items ?)
