### ISSUE TITLE
RefundPlugin/src/Entity/ShipmentTrait.php misses constructor part for collection initialization

### ISSUE THREAD

**Issue by diimpp** [Sylius/RefundPlugin#277]
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/Shipment.php#L42

**Comment by GSadee** [comment]
Adding collection initialization is a part of [installation guide](https://github.com/Sylius/RefundPlugin#installation) and it was mentioned in [UPGRADE file](https://github.com/Sylius/RefundPlugin/blob/master/UPGRADE.md#upgrade-from-100-rc5-to-100-rc6)
