### ISSUE TITLE
Javascripts are not working with webpack

### ISSUE THREAD

**Issue by andriusvo** [Sylius/RefundPlugin#319]
Sylius versions affected - v1.9.4 (and others, which are using webpack)

Error: `$ is undefined` in `_javascripts.html.twig` while using webpack in sylius.

**Comment by kulczy** [comment]
Hi @andriusvo we're not officially using webpack yet, but`$ is undefined in _javascripts.html.twig` may mean that the script from this file is called before you load the jquery library, so try to load `_javascripts.html.twig` file after your main js files

**Comment by andriusvo** [comment]
It's loaded after main javascript files are required:

`
{{ encore_entry_script_tags('admin-entry', null, 'admin') }}
`

**Comment by kulczy** [comment]
so jQuery is missing. Webpack Encore has a [quick solution](https://symfony.com/doc/current/frontend/encore/legacy-applications.html)

**Comment by andriusvo** [comment]
> so jQuery is missing. Webpack Encore has a [quick solution](https://symfony.com/doc/current/frontend/encore/legacy-applications.html)

Thanks, will check.
