### ISSUE TITLE
[Bug] Not using mapped-superclass breaks extension

### ISSUE THREAD

**Issue by aleho** [Sylius/RefundPlugin#352]
**SyliusRefundPlugin version affected**: 1.1

**Description**  
Most definitions already use mapped-superclass instead of entity, except for
- `CreditMemoSequence`
- `CustomerBillingData`
- `ShopBillingData`.

This breaks extension via `sylius_resource:`.

**Possible Solution**  
Replace `<entity` with `<mapped-superclass`.

**Comment by laurentdabbb** [comment]
Hi,
I need to extend ShopBillingData... I confirm this issue.
Thanks a lot for this PR.
