### ISSUE TITLE
Change credit memos grid icon

### ISSUE THREAD

**Issue by bartoszpietrzak1994** [Sylius/RefundPlugin#37]
It would be nice to change icon displayed next to `Credit Memos` since Invoices have the same one.

![image 1](https://user-images.githubusercontent.com/22262296/44336786-cf8daf00-a478-11e8-81af-290acb4b92c2.png)

**Comment by Zales0123** [comment]
It will be fixed by https://github.com/Sylius/InvoicingPlugin/pull/61

**Comment by Zales0123** [comment]
Resolved by https://github.com/Sylius/InvoicingPlugin/pull/61
