### ISSUE TITLE
Add new attribute  into creditMemo entity

### ISSUE THREAD

**Issue by ajaysSymfonyExpert** [Sylius/RefundPlugin#377]
How can we override creditMemo Entity to add few new attributes

**Comment by GSadee** [comment]
Hello @ajaysSymfonyExpert!

I hope that this [Customization Guide](https://docs.sylius.com/en/1.12/cookbook/payments/customizing-credit-memo.html) should help you, but if you have other problems or questions, please, use our [Slack](https://sylius-slackin.herokuapp.com/) or stackoverflow 😃

**Comment by ajaysSymfonyExpert** [comment]
> Hello @ajaysSymfonyExpert!
> 
> I hope that this [Customization Guide](https://docs.sylius.com/en/1.12/cookbook/payments/customizing-credit-memo.html) should help you, but if you have other problems or questions, please, use our [Slack](https://sylius-slackin.herokuapp.com/) or stackoverflow 😃

Thank you so much @GSadee
