### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/RefundPlugin#397]
Hello,

I can't find a way to use this plugin, I have to implement the gateway usage and I don't understand the code.

Some documentation, even an exemple would help.

**Comment by vvasiloi** [comment]
Here's an example: https://github.com/Setono/SyliusQuickpayRefundBridgePlugin

**Comment by vasilvestre** [comment]
There's a lot of way to extend the plugin, so far using event listener and native refund units worked.
