### ISSUE TITLE
A transition from a place/state must have an unique name. Multiple transitions named "complete" from place/state "new" were found on StateMachine "sylius_refund_refund_payment".

### ISSUE THREAD

**Issue by Dev-patel1882** [Sylius/RefundPlugin#430]
When I build composer in Docker, I encounter this error:

"A transition from a place/state must have a unique name. Multiple transitions named 'complete' from place/state 'new' were found on StateMachine 'sylius_refund_refund_payment'."
![Screenshot from 2024-05-16 17-30-24](https://github.com/Sylius/RefundPlugin/assets/128371272/44ad5508-b3e9-40af-8bd5-f099c2fb0c45)

**Comment by vvasiloi** [comment]
Remove this import:
![image](https://github.com/Sylius/RefundPlugin/assets/7114562/b4b98677-3347-45db-8ee0-108e48aa94e6)

**Comment by TakesTheBiscuit** [comment]
i don't believe that is a perfect fix - refund plugin is failing because of some internal change, i guess because it calls sylius 1.12 or 1.13 and that may have altered how it handles StateMachine?

**Comment by Dev-patel1882** [comment]
@vvasiloi , we tried this but it's not working. Can you please provide another solution? Thank you
