### ISSUE TITLE
Wrong shipping refund total

### ISSUE THREAD

**Issue by Zales0123** [Sylius/RefundPlugin#65]
Even if Shipping was partially refunded, the displayed shipping refund total is shipping total (the total of credit memo and totals of refunded order item units ar correct)

**Comment by Zales0123** [comment]
<img width="1140" alt="zrzut ekranu 2018-09-19 o 09 02 33" src="https://user-images.githubusercontent.com/6212718/45736529-83569b80-bbeb-11e8-8500-c1876435ac2c.png">

**Comment by laurent35240** [comment]
Fixed in this PR https://github.com/Sylius/RefundPlugin/pull/94
