### ISSUE TITLE
Improve refund payments UI

### ISSUE THREAD

**Issue by Zales0123** [Sylius/RefundPlugin#78]
<img width="846" alt="zrzut ekranu 2018-10-01 o 16 15 19" src="https://user-images.githubusercontent.com/6212718/46295255-e525e680-c597-11e8-88e9-f177cda7f6a7.png">

- [ ] ugly empty column if no action is possible
- [ ] status should be displayed as some label rather than regular string

**Comment by laurent35240** [comment]
PR for this issue available her #95
