### ISSUE TITLE
Improve "fully refunded" label

### ISSUE THREAD

**Issue by Zales0123** [Sylius/RefundPlugin#79]
<img width="112" alt="zrzut ekranu 2018-10-01 o 16 36 26" src="https://user-images.githubusercontent.com/6212718/46295389-3930cb00-c598-11e8-99ec-f638fcabc2ab.png">

It could have an icon and some more sophisticated color

**Comment by Zales0123** [comment]
Sorry, my bad, in fact, there is a `fully_refunded` twig template for this state, but I did not copy it is not copy into the test application to make it visible 😄 And the icon is wrong, now it is `checked` rather than `check`. So resolving this issue would be:

1. copying `src/Resources/views/SyliusAdminBundle` to `tests/Application/templates/bundles`
2. changing icon class to `checked` or any other [semantic ui icon](https://semantic-ui.com/elements/icon.html) that seems proper :)

**Comment by geryjuhasz** [comment]
https://github.com/Sylius/RefundPlugin/pull/81

**Comment by Zales0123** [comment]
Should be fixed now
