### ISSUE TITLE
sylius_mailer.sender configuration overriden by this bundle

### ISSUE THREAD

**Issue by Prometee** [Sylius/RefundPlugin#93]
I just install this plugin and it appears that my emails are now sending with a name and an email that I don't configure.

Is there a reason of overriding the sender in this plugin ?

If not I suggest to remove it and also to rename the configuration file in the recipe to `config/packages/_sylius_refund.yaml` to allow override of this bundle configuration.

Maybe it will also be a good practice for all Sylius plugins which overrides other Sylius bundle configurations.

**Comment by Zales0123** [comment]
I'm 100% sure it's an unnecessary overwrite, thank you for reporting this bug, I'll try to fix it asap :)

**Comment by Zales0123** [comment]
Mailer is not overridden anymore 🐎
