### ISSUE TITLE
Make it clearer that wkhtmltopdf is required

### ISSUE THREAD

**Issue by laurent35240** [Sylius/RefundPlugin#98]
While writing BDD tests locally, I got stuck because wkhtmlpdf was not installed on my local environment.
I think it will be a good idea to add into the README or somewhere else in documentation this requirement.

I think we can also remove the bin here https://github.com/Sylius/RefundPlugin/blob/master/tests/Application/etc/wkhtmltopdf and add instead installation of this bin in travis build.

Like that every one can more easily launch behat tests even if they are not on linux.

Let me know what you think about it and if it is ok for you I will write a PR for it.

**Comment by lempere** [comment]
For newcomers, you can paste the wkhtmltopdf.exe in Application/etc (for windows environments) and past the tests.

**Comment by bartoszpietrzak1994** [comment]
Hello laurent35240,

Indeed, the requirement is missing in the README.md file and it should be fixed as soon as possible.

When it comes to downloading the binary, we wanted to avoid build failing once the download website is unavailable. What's more, as far as I remember, after a few builds, Travis CI was blocked by the host for requesting the binary too often.
